### PR TITLE
Implement Node.replaceChild()

### PR DESCRIPTION
**Pull request by pitbuster**

### CODE REVIEW

**Comment by b-fuze** [comment]
Thank you for the PR, however, it needs to check that `oldChild` is in fact a child of the parent node. You can check the code of `replaceWith` on how to access the parent node's mutator, from there you can use `indexOf` to insure that it is indeed a descendant of the parent.

**Comment by pitbuster** [comment]
@b-fuze Good catch, I will fix that.

**Comment by pitbuster** [comment]
@b-fuze: I think checking that `oldChild.parentNode === this` or I am missing something?

**Comment by b-fuze** [comment]
Oh, you're right. Yup, that works too xD

I think an error should be thrown, similar to how browsers work.

**Comment by b-fuze** [comment]
Thanks

**Pull request merged**
