### PR TITLE
add a CI that checks formatting and run tests

### PR DESCRIPTION
**Pull request by Hunam6**
depends on #86, should be merged after

I didn't format the code on purpose to ensure that the CI really fails if the code isn't formatted.

### CODE REVIEW

**Comment by Hunam6** [comment]
Can you run the CI to test it please?

**Comment by b-fuze** [comment]
Hrm, the release plugin is failing... I'll have to remove that branch from the `pull-request` trigger, or can you do that?

**Comment by Hunam6** [comment]
For now I've disabled testing on Windows because of this issue: https://github.com/b-fuze/deno-dom/runs/5753986401?check_suite_focus=true.

**Comment by b-fuze** [comment]
It not working on Windows is fine. I completely forgot that `deno fmt` runs on Markdown as well lol. I'll take out the native plugin building step and move it into its own GHA Workflow.

Otherwise, looks good. Thanks

**Pull request merged**
